common:
  api:
    base-url: ""
    api-key: ""
server:
  port: 8085
  servlet:
    contextPath: /bmg13
management:
  endpoints:
    metrics:
      enabled: true
    web:
      exposure:
        include: '*'
spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: localhost:9200
      repositories:
        enabled: true